
# Generated by CodiumAI

import pytest

class TestNumTest:

    # Test with a number greater than or equal to 18
    def test_num_greater_than_or_equal_to_18(self):
        num_test(18)
        # Assert that the output is "Eligible for voting"
        # You can use the 'capfd' fixture to capture the output and assert on it

